/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './ngx-item.component';
const styles_NgxItemComponent:any[] = ['.item[_ngcontent-%COMP%] {\n        display: inline-block;\n        white-space: initial;\n    }'];
export const RenderType_NgxItemComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:0,
    styles:styles_NgxItemComponent,data:{}});
export function View_NgxItemComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'div',[['class',
      'item']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      i0.ɵncd((null as any),0)],(null as any),(null as any));
}
export function View_NgxItemComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'ngx-item',([] as any[]),
      (null as any),(null as any),(null as any),View_NgxItemComponent_0,RenderType_NgxItemComponent)),
      i0.ɵdid(114688,(null as any),0,i1.NgxItemComponent,([] as any[]),(null as any),
          (null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const NgxItemComponentNgFactory:i0.ComponentFactory<i1.NgxItemComponent> = i0.ɵccf('ngx-item',
    i1.NgxItemComponent,View_NgxItemComponent_Host_0,{},{},['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvU2hlaWsgQWx0aGFmL0Rlc2t0b3AvUHJvamVjdHMvbmd4LWNhcm91c2VsL3NyYy9uZ3gtaXRlbS9uZ3gtaXRlbS5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvU2hlaWsgQWx0aGFmL0Rlc2t0b3AvUHJvamVjdHMvbmd4LWNhcm91c2VsL3NyYy9uZ3gtaXRlbS9uZ3gtaXRlbS5jb21wb25lbnQudHMiLCJuZzovLy9DOi9Vc2Vycy9TaGVpayBBbHRoYWYvRGVza3RvcC9Qcm9qZWN0cy9uZ3gtY2Fyb3VzZWwvc3JjL25neC1pdGVtL25neC1pdGVtLmNvbXBvbmVudC50cy5OZ3hJdGVtQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9DOi9Vc2Vycy9TaGVpayBBbHRoYWYvRGVza3RvcC9Qcm9qZWN0cy9uZ3gtY2Fyb3VzZWwvc3JjL25neC1pdGVtL25neC1pdGVtLmNvbXBvbmVudC50cy5OZ3hJdGVtQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdiBjbGFzcz1cIml0ZW1cIj48bmctY29udGVudD48L25nLWNvbnRlbnQ+PC9kaXY+IiwiPG5neC1pdGVtPjwvbmd4LWl0ZW0+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTthQUFrQjs7O29CQ0FsQjtNQUFBO2FBQUE7VUFBQTtJQUFBOzs7OyJ9
