/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './ngx-item.component';
const styles_NgxItemComponent:any[] = ['[_nghost-%COMP%] {\n        display: inline-block;\n        white-space: initial;\n        vertical-align: top;\n    }'];
export const RenderType_NgxItemComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:0,
    styles:styles_NgxItemComponent,data:{}});
export function View_NgxItemComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[i0.ɵncd((null as any),0)],(null as any),(null as any));
}
export function View_NgxItemComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'ngx-item',([] as any[]),
      [[8,'className',0]],(null as any),(null as any),View_NgxItemComponent_0,RenderType_NgxItemComponent)),
      i0.ɵdid(49152,(null as any),0,i1.NgxItemComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(_ck,_v) => {
    const currVal_0:any = i0.ɵnov(_v,1).classes;
    _ck(_v,0,0,currVal_0);
  });
}
export const NgxItemComponentNgFactory:i0.ComponentFactory<i1.NgxItemComponent> = i0.ɵccf('ngx-item',
    i1.NgxItemComponent,View_NgxItemComponent_Host_0,{},{},['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvU2hlaWsgQWx0aGFmL0Rlc2t0b3AvUHJvamVjdHMvbmd4LWNhcm91c2VsL3NyYy9uZ3gtaXRlbS9uZ3gtaXRlbS5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvU2hlaWsgQWx0aGFmL0Rlc2t0b3AvUHJvamVjdHMvbmd4LWNhcm91c2VsL3NyYy9uZ3gtaXRlbS9uZ3gtaXRlbS5jb21wb25lbnQudHMiLCJuZzovLy9DOi9Vc2Vycy9TaGVpayBBbHRoYWYvRGVza3RvcC9Qcm9qZWN0cy9uZ3gtY2Fyb3VzZWwvc3JjL25neC1pdGVtL25neC1pdGVtLmNvbXBvbmVudC50cy5OZ3hJdGVtQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9DOi9Vc2Vycy9TaGVpayBBbHRoYWYvRGVza3RvcC9Qcm9qZWN0cy9uZ3gtY2Fyb3VzZWwvc3JjL25neC1pdGVtL25neC1pdGVtLmNvbXBvbmVudC50cy5OZ3hJdGVtQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPG5nLWNvbnRlbnQ+PC9uZy1jb250ZW50PiIsIjxuZ3gtaXRlbT48L25neC1pdGVtPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7OzJCQ0FBOzs7b0JDQUE7TUFBQTthQUFBO1VBQUE7SUFBQTtJQUFBLFdBQUEsU0FBQTs7OzsifQ==
